---
name: Codespell

on:
  push:
    branches: [master, v2]
  pull_request:
    branches: [master, v2]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
